### ISSUE TITLE
Compliance with PHP Specification for class names

### ISSUE THREAD

**Issue by yborovikov** [box/augmented_types#20]
[PHP Specification](http://php.net/manual/en/language.oop5.basic.php) defines class names that match ^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*$ regex as valid.

Current AT lexer pattern for names doesn't allow characters in the \x7F - \xFF ([extended ASCII](http://www.ascii-code.com/)) range, causing "*syntax error, unexpected UNKNOWN, expecting $end*" error messages.

**Comment by jmarrama** [comment]
Everything is merged, closing the issue
