### ISSUE TITLE
Return type ignored

### ISSUE THREAD

**Issue by Whyounes** [box/augmented_types#23]
``` php
/**
 * SSH to server.
 *
 * @param   string      $url
 * @param   int|void    $port
 * @return  int
 */
function ssh($url, $port = 2222)
{
    return "something";
}

ssh("http://url.net"); // not using return value
$ret = ssh("http://url.net"); // using return value
```

If I call the above function without using the return value nothing happens, but it throws a fatal error if I did!
Can you please explain to me this behavior?

**Note:** I tested the snippet on PHP7 and I got the same thing.

**Comment by Whyounes** [comment]
I found the answer on the [doc](https://github.com/box/augmented_types/wiki/Type-Annotation-Requirements#the-return-declaration-must-be-satisfied).

Thanks :)

**Comment by jmarrama** [comment]
Np! Also happy to hear this extension works in PHP7 - I hadn't tested that. Super cool!
